---
- hosts: localhost
  gather_facts: false
  
  tasks:

    - name: Hi
      debug: 
        msg: "hi from alpine python playbook"

    - name: Sleep for 30 seconds and continue with play
      wait_for:
        timeout: 30