---
- hosts: localhost
  gather_facts: true
  vars:
    troubleshoot: false
  tasks:       

    - name: Get OS
      debug:
        var: ansible_distribution

    - name: Run proper setup for {{ ansible_distribution }}
      include_tasks: "{{ ansible_distribution }}.yml"
