---
- hosts: all
  gather_facts: true
  vars:
    troubleshoot: false
  tasks:       

    - name: Ensure OS is compatible
      assert:
        that:
          ansible_distribution == "Amazon"
        fail_msg: OS must be Amazon Linux 2.

    - name: Update repo
      package:
        name: '*'
        state: latest
        update_cache: true
      become: true

    - name: Add Azure-cli to yum repository
      yum_repository:
        name: azure-cli
        description: Microsoft Azure CLI
        baseurl: https://packages.microsoft.com/yumrepos/azure-cli
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: yes
        enabled: yes
      become: true

    - name: Enable Docker yum repo for Amazon Linux 2
      command: amazon-linux-extras enable docker
      become: true

    - name: Install developer packages (azure, git, python)
      package:
        name: zip, unzip, python-pip, polkit, azure-cli, git, docker
        state: latest
      become: true

    - name: Install developer packages (boto)
      pip:
        name:
        - chardet2
        - urllib3
        - requests # Python Requests module
        - boto3 # AWS SDK
        - boto # AWS SDK
        - botocore # AWS SDK
        - pywinrm # Windows Python manager module
        - pyvmomi # VMWare SDK
        state: latest
        extra_args: --user
      become: true
      become_user: ec2-user

    - name: Get latest version of terraform
      shell: curl https://www.terraform.io/downloads.html | grep -A1 'linux' | sed -n 's/.*href="\(.*\)".*/\1/p'
      args:
        warn: false
      register: terraform
      
    - name: Install developer packages (terraform)
      unarchive:
        src: "{{ terraform.stdout_lines[1] }}"
        dest: /usr/local/bin/
        remote_src: yes
      become: true

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present
      become: true
    
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      become: true
