---
- hosts: localhost
  gather_facts: true
  vars:
    troubleshoot: false
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:       

    - name: Ensure OS is compatible
      assert:
        that:
          ansible_distribution == "Amazon"
        fail_msg: OS must be Amazon Linux 2.

    - name: Update repo
      dnf:
        name: '*'
        state: latest
        update_cache: true

    - name: Add Azure-cli to yum repository
      yum_repository:
        name: azure-cli
        description: Microsoft Azure CLI
        baseurl: https://packages.microsoft.com/yumrepos/azure-cli
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: yes
        enabled: yes

    - name: Install developer packages (azure, git, python)
      package:
        name: python3-pip
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/python

    - name: Install developer packages (boto)
      pip:
        name:
        - chardet2
        - urllib3
        - requests # Python Requests module
        - boto3 # AWS SDK
        - boto # AWS SDK
        - botocore # AWS SDK
        - pywinrm # Windows Python manager module
        - pyvmomi # VMWare SDK
        state: latest
        extra_args: --user

    - name: Get latest version of terraform
      shell: curl https://www.terraform.io/downloads.html | grep -A1 'linux' | sed -n 's/.*href="\(.*\)".*/\1/p'
      args:
        warn: false
      register: terraform
      
    - name: Install developer packages (terraform)
      unarchive:
        src: "{{ terraform.stdout_lines[1] }}"
        dest: /usr/local/bin/
        remote_src: yes
