---
- hosts: localhost
  gather_facts: false
  vars:
    jenkins_network: jenkins_network
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:

    # - name: container runs me
    #   debug:
    #     var: container_message
    #   failed_when: container_message != "bob"
    #   tags: container_message


    # - name: create cronjob
    #   cron:
    #     name: namedpipe for Jenkins container
    #     special_time: reboot
    #     job: while true; do eval "$(cat /home/ec2-user/ansible/jenkins/jenkinspipe)"; done
    #   tags: create_cron

    # - name: Ensure docker service is started
    #   service:
    #     name: docker
    #     state: started
    #     enabled: yes
    #   become: true
    #   tags: docker_service

    # - name: Install package depd
    #   yum:
    #     name:
    #       - python3-pip
    #   become: true

    # - name: Install pip depenencies
    #   pip:
    #     name:
    #       - docker
    #     state: latest
    #     extra_args: --user

    - name: Create a network
      docker_network:
        name: "{{ jenkins_network }}"

    - name: Create jenkins volume
      docker_volume:
        name: jenkins_home

    - name: Start Jenkins
      docker_container:
        name: jenkins
        image: jenkins/jenkins
        volumes:
          - /home/ec2-user/jenkins/jenkins_home/:/var/jenkins_home/" # must chown -R 1000:1000 the local directory
          - /home/ec2-user/jenkins/:/hostpipe
        ports:
          - 0.0.0.0:80:8080
          - 50000:50000
        restart_policy: unless-stopped
        networks:
          - name: "{{ jenkins_network }}"
      tags: start_jenkins

    - name: ansible container
      docker_container:
        name: amalin-ansible
        image: amalin-ansible:latest
        #volumes:
        #  - /home/ec2-user/jenkins/:/hostpipe
        state: started
        restart_policy: unless-stopped
        networks:
          - name: "{{ jenkins_network }}"
        ports:
          - 0.0.0.0:7655:22
        #   - jenkins:7655:22
        command: sleep infinity
      tags: ansible_container
